[[bin]]
name = "River"
path = "Source/River.rs"

[build-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
toml = { version = "0.8.20" }

[dependencies]
Echo = { version = "0.0.1", path = "../Echo" }
async-trait = "0.1.88"
futures = { version = "0.3.31" }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
unbug = { version = "0.4.0" }

[features]
default = []

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "River"
description = "River 🌊"
edition = "2024"
license-file = "LICENSE"
name = "River"
publish = false
repository = "https://github.com/CodeEditorLand/River"
version = "0.0.1"
